/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {

        // Hyperlink hylink = new Hyperlink();
        // hylink.testcase01();
        // hylink.endTest();

        // Amazon amaz = new Amazon();
        // amaz.testcase01();
        // amaz.endTest();

        // Linkedin link = new Linkedin();
        // link.testcase01();
        // link.endTest();

        // imageUrls image = new imageUrls();
        // image.testcase01();
        // image.endTest();

        // Frames obj = new Frames();
        // obj.testcase01();
        // obj.endTest();

        // idmbRating obj = new idmbRating();
        // obj.testcase01();
        // obj.endTest();

        // Windows obj = new Windows();
        // obj.testcase01();
        // obj.endTest();


    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
